(()=>{'use strict';
const K='kimse.p0.state',CENTER='https://www.nid.or.kr/info/facility_list.aspx';
const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I=n=>'<i class="ti ti-'+n+'" aria-hidden="true"></i>';
const read=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return {}}};
const write=s=>localStorage.setItem(K,JSON.stringify(s));
const route=()=>String(location.hash||'#/start').slice(2).split('?')[0];
const labels={sleep_minutes:'수면시간',steps:'걸음수',location_radius_m:'생활반경',movement_distance_m:'이동거리',outings:'외출',motion_active_minutes:'활동시간',app_active_minutes:'낌새 이용시간',call_count:'통화 횟수',call_duration_min:'통화시간',messaging_sessions:'메신저 활동',task_response_ms:'반응시간',voice_pause_ratio:'말할 때 멈춤'};
function fmt(k,v){const n=Number(v);if(!Number.isFinite(n))return '-';if(k==='sleep_minutes'){const m=Math.round(n);return Math.floor(m/60)+'시간 '+m%60+'분'}if(k==='steps')return Math.round(n).toLocaleString('ko-KR')+'보';if(k==='voice_pause_ratio')return Math.round(n*100)+'%';if(k==='location_radius_m'||k==='movement_distance_m')return n>=1000?(n/1000).toFixed(1)+'km':Math.round(n)+'m';if(k==='motion_active_minutes'||k==='app_active_minutes'||k==='call_duration_min')return Math.round(n)+'분';return Math.round(n*100)/100+''}
function data(){const s=read(),m=s.monitoring?.summary||{},ch=(Array.isArray(m.changes)?m.changes:[]).filter(x=>x&&x.changed!==false).slice(0,6),days=Number(m.baseline_days)||0;return {s,m,days:days||14,changes:ch.map(x=>{const p=Math.round(Number(x.relative_change||0)*100);return {label:labels[x.metric]||x.metric,p,dir:p>0?'증가':p<0?'감소':'변화 없음',baseline:fmt(x.metric,x.baseline),recent:fmt(x.metric,x.recent)}})}}
function textSummary(){const d=data(),c=d.changes.length?d.changes.map(x=>x.label+' '+(x.p>0?'+':'')+x.p+'%').join(', '):'확인된 큰 변화 없음';return ['낌새 상담 준비 요약','개인 기준선: '+d.days+'일','최근 변화 기간: 최근 3일','변화 신호: '+c,'보호자 공유 동의: '+(d.s.consents?.caregiverShare?'예':'아니오'),'진단 결과가 아니며 전문 평가 시 참고 자료입니다.','치매상담콜센터: 1899-9988'].join('\n')}
function notify(msg){const n=document.querySelector('#announcer');if(n){n.textContent='';setTimeout(()=>n.textContent=msg,10)}let t=document.querySelector('.govtech-toast');if(!t){t=document.createElement('div');t.className='govtech-toast';t.setAttribute('role','status');document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(notify._t);notify._t=setTimeout(()=>t.classList.remove('show'),2400)}
async function share(){const t=textSummary();try{if(navigator.share){await navigator.share({title:'낌새 상담 준비 요약',text:t})}else if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(t)}else throw 0;const s=read();s.govShare={lastSharedAt:new Date().toISOString()};write(s);notify(navigator.share?'변화 요약을 공유했습니다.':'변화 요약을 복사했습니다.');return}catch(e){if(e?.name!=='AbortError')notify('이 기기에서는 바로 공유할 수 없습니다. 상담 준비 리포트를 이용해주세요.')}}

function monitoring(screen){const a=screen.querySelector('a[href="tel:18999988"]');if(!a||a.dataset.gov)return;const span=a.querySelector(':scope > span');if(span)span.innerHTML='<small>1899-9988 · 공식 상담</small><strong>치매상담콜센터</strong>';a.setAttribute('aria-label','치매상담콜센터 1899-9988 전화 연결');a.dataset.gov='1'}
function consent(screen){if(sessionStorage.getItem('kimse.gov.sharePending')!=='1'||screen.querySelector('.gov-consent-guide'))return;const f=screen.querySelector('#consent-form');if(!f)return;const x=document.createElement('div');x.className='gov-consent-guide';x.innerHTML=I('users')+'<div><strong>보호자 공유 동의를 먼저 확인해주세요</strong><p>‘보호자와 변화 알림 공유’를 선택하고 저장하면 최근 변화 화면으로 돌아갑니다.</p></div>';f.prepend(x)}
function home(){if(sessionStorage.getItem('kimse.gov.sharePending')!=='1')return;const s=read();if(s.consents?.caregiverShare){sessionStorage.removeItem('kimse.gov.sharePending');setTimeout(()=>{if(route()==='home')location.hash='#/monitoring-status'},180)}}
function settings(screen){if(screen.querySelector('.gov-report-settings-link'))return;const list=screen.querySelector('.list');if(!list)return;const a=document.createElement('a');a.className='list-row gov-report-settings-link';a.href='#/report';a.innerHTML='<span><strong>상담 준비 리포트</strong><small>14일 기준선과 최근 변화를 상담용으로 정리합니다.</small></span>'+I('chevron-right');const m=[...list.children].find(x=>x.getAttribute?.('href')==='#/monitoring-status');m?m.after(a):list.append(a)}
function caregiver(screen){if(screen.querySelector('.gov-care-summary'))return;const d=data(),sec=document.createElement('section');sec.className='gov-care-summary';const rows=d.changes.slice(0,3).map(x=>'<li><span>'+esc(x.label)+'</span><strong>'+(x.p>0?'+':'')+x.p+'% · '+x.dir+'</strong></li>').join('');sec.innerHTML='<div class="gov-care-summary-head">'+I('shield-check')+'<div><small>사용자가 동의한 범위</small><h2>'+(d.s.consents?.caregiverShare?'공유된 변화 요약':'보호자 공유 대기')+'</h2></div></div>'+(d.s.consents?.caregiverShare?'<ul>'+rows+'</ul><a class="btn-kimse btn-secondary-k btn-full" href="#/report">상담 준비 리포트 보기</a>':'<p>사용자가 보호자 공유에 동의하면 최근 변화 요약을 확인할 수 있습니다.</p>');(screen.querySelector('.summary-card')||screen.querySelector('.page-title'))?.after(sec)}
function report(screen){if(screen.dataset.govReport)return;const d=data(),s=d.s,footer=screen.querySelector('.app-footer')?.outerHTML||'',changes=d.changes.length?d.changes.map(x=>'<li><div><span>'+esc(x.label)+'</span><small>14일 평균 '+esc(x.baseline)+' → 최근 '+esc(x.recent)+'</small></div><strong>'+(x.p>0?'+':'')+x.p+'%<em>'+x.dir+'</em></strong></li>').join(''):'<li class="empty">현재 확인된 큰 변화가 없습니다.</li>';const confirms=[s.mood?'사용자 기분 기록: '+s.mood:'',s.health?.memo?'사용자 메모: '+s.health.memo:'','보호자 공유: '+(s.consents?.caregiverShare?'동의됨':'동의하지 않음')].filter(Boolean);screen.innerHTML='<div class="eyebrow">상담 준비</div><h1 class="page-title">상담 전에 보여줄<br>변화 요약입니다</h1><p class="page-desc">실제 생활기록과 변화값만 한 장에 모았습니다.</p><section class="gov-report-notice">'+I('info-circle')+'<div><strong>진단 결과가 아닙니다</strong><p>문진·검사할 때 생활 변화의 참고 자료로 사용할 수 있습니다.</p></div></section><section class="gov-report-card"><h2>개인 기준선과 최근 변화</h2><div class="gov-report-period"><span><small>기준선</small><strong>'+d.days+'/14일</strong></span><span><small>최근 변화</small><strong>최근 3일</strong></span></div></section><section class="gov-report-card"><h2>평소와 달라진 생활신호</h2><ul class="gov-report-changes">'+changes+'</ul></section><section class="gov-report-card"><h2>사용자·보호자 확인</h2><ul class="gov-confirm-list">'+confirms.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></section><section class="gov-report-card"><h2>전문평가 시 참고 요약</h2><p>'+(d.changes.length?'최근 3일 동안 '+d.changes.map(x=>x.label).join('·')+' 변화가 같은 시기에 관찰되었습니다. 한 신호만으로 판단하지 않고 14일 개인 기준선과 함께 확인해주세요.':'현재 큰 변화가 확인되지 않았습니다. 지속되는 불편이 있다면 기록과 함께 상담해주세요.')+'</p></section><div class="gov-flow-strip"><span>근거</span><i>→</i><span>관찰 신호</span><i>→</i><span>14일 기준선</span><i>→</i><span>복수 변화</span><i>→</i><span>상담·지원</span></div><section class="gov-public-actions"><div><small>공공서비스 연결</small><h2>다음 행동으로 바로 이어집니다</h2></div><a href="tel:18999988">'+I('phone')+'<span><small>치매상담콜센터</small><strong>1899-9988 전화하기</strong></span></a><a href="'+CENTER+'" target="_blank" rel="noopener">'+I('building-community')+'<span><small>중앙치매센터 공식 정보</small><strong>가까운 치매안심센터 찾기</strong></span></a></section><div class="gov-report-actions"><button class="btn-kimse btn-primary-k" data-gov-share>'+I('share-2')+' 보호자와 요약 공유</button><button class="btn-kimse btn-secondary-k" data-gov-print>'+I('printer')+' 인쇄·PDF 저장</button></div>'+footer;screen.dataset.govReport='1'}
function demoPanel(screen){if(!location.hash.includes('govtech=1')||screen.querySelector('.gov-demo-panel'))return;const p=document.createElement('section');p.className='gov-demo-panel';p.innerHTML='<strong>GovTech 실제 제품 시연</strong><p>14일 장기 데이터만 검증 입력을 사용하고 이후 화면은 실제 제품 UI를 그대로 사용합니다.</p><button class="btn-kimse btn-primary-k btn-full" data-gov-demo>시연 시작</button>';screen.append(p)}
function seedAndRun(){const s=read(),now=Date.now(),day=n=>new Date(now-n*86400000).toISOString();sessionStorage.setItem('kimse.gov.demo.original',localStorage.getItem(K)||'');Object.assign(s,{account:s.account||{name:'GovTech 시연 사용자',email:''},self:true,care:true,mode:'self'});s.onboarding={profileDone:true,initialDone:true,consentDone:true,completed:true};s.initial={...(s.initial||{}),completedAt:new Date().toISOString(),domains:{memory:86,executive:84,language:87,spatial:85,daily:88}};s.consents={...(s.consents||{}),service:true,privacy:true,health:true,caregiverShare:true};s.baseline={startedAt:day(15)};s.monitoring={...(s.monitoring||{}),summary:{status:'READY',baseline_days:14,baseline_target_days:14,level:'ATTENTION',changes:[{metric:'sleep_minutes',baseline:425,recent:336,relative_change:-.2094,changed:true},{metric:'steps',baseline:5120,recent:3460,relative_change:-.3242,changed:true},{metric:'voice_pause_ratio',baseline:.18,recent:.23,relative_change:.2778,changed:true}],interpretation:'진단 결과가 아니라 변화 관찰 참고 정보입니다.'},alerts:[{id:'gov-demo',detected_at:new Date().toISOString()}]};s.caregivers=[{name:'가족 보호자',relation:'자녀'}];write(s);const seq=[['evidence-proof',2800],['baseline',2600],['monitoring-status',3800],['report',4800],['caregiver-home',3200],['report',3600]];(async()=>{for(const [r,ms] of seq){location.hash='#/'+r;await new Promise(x=>setTimeout(x,ms))}})()}
function enhance(){const screen=document.querySelector('#main');if(!screen)return;const r=route();if(r==='monitoring-status')monitoring(screen);if(r==='consent')consent(screen);if(r==='home')home();if(r==='settings')settings(screen);if(r==='caregiver-home')caregiver(screen);if(r==='report')report(screen);if(r==='demo-capture')demoPanel(screen)}
let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{q=false;enhance()}))}new MutationObserver(schedule).observe(document.querySelector('#app'),{childList:true,subtree:true});window.addEventListener('hashchange',schedule);schedule();
document.addEventListener('click',async e=>{const x=e.target.closest('[data-share-monitoring]');if(x){const s=read();e.preventDefault();e.stopImmediatePropagation();if(!s.consents?.caregiverShare){sessionStorage.setItem('kimse.gov.sharePending','1');location.hash='#/consent'}else await share();return}if(e.target.closest('[data-gov-share]')){e.preventDefault();await share()}if(e.target.closest('[data-gov-print]')){e.preventDefault();window.print()}if(e.target.closest('[data-gov-demo]')){e.preventDefault();seedAndRun()}},true);
})();