(()=>{'use strict';
const $=s=>document.querySelector(s),A=$('#app'),N=$('#announcer'),O=$('#offline-banner'),K='kimse.p0.state';
const D={account:null,intent:null,self:false,care:false,mode:'self',caregivers:[],plan:'FREE',q:0,answers:[],med:false,mood:'좋아요',a11y:{largeText:false,highContrast:false,voiceGuidance:false,captions:true,largeTouchTargets:true,colorIcons:true,screenReader:true,reduceMotion:false}};
let S=Object.assign(structuredClone(D),JSON.parse(localStorage.getItem(K)||'{}'));
const save=()=>{localStorage.setItem(K,JSON.stringify(S));applyA11y()},go=p=>location.hash='#/'+p,route=()=>(location.hash||'#/start').slice(2).split('?')[0];
const say=t=>{N.textContent='';setTimeout(()=>N.textContent=t,10);if(S.a11y.voiceGuidance&&speechSynthesis){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='ko-KR';u.rate=.9;speechSynthesis.speak(u)}};
const I=n=>`<i class="ti ti-${n}" aria-hidden="true"></i>`,btn=(t,p,c='btn-primary-k')=>`<button class="btn-kimse ${c} btn-full" data-go="${p}">${t}</button>`;
function demo(){if(S.account)return;S.account={name:'김○○',email:'kimse@example.com'};S.self=true;save()}
function head(t='낌새',back=true){return `<header class="app-header"><div class="app-header-inner">${back?`<button class="icon-button" data-back aria-label="이전 화면">${I('chevron-left')}</button>`:`<a class="brand" href="#/home"><span class="brand-mark" aria-hidden="true">낌</span><span>낌새<small class="brand-sub">작은 변화를 먼저 알아차려요</small></span></a>`}<strong>${back?t:''}</strong><a class="icon-button" href="#/settings" aria-label="설정">${I('settings')}</a></div></header>`}
const foot=()=>`<div class="app-footer">Updated 2026.09.12 · Release 01<br>의료 진단을 대신하지 않으며 변화 관찰과 기록을 돕습니다.</div>`;
function nav(care=false,active=route()){let x=care?[['home','caregiver-home','홈'],['bell','emergency','알림'],['users','family','가족'],['chart-line','report','리포트'],['dots','settings','더보기']]:[['home','home','홈'],['checkbox','assessment-start','체크'],['barbell','training','훈련'],['clipboard-heart','health','기록'],['dots','settings','더보기']];return `<nav class="bottom-nav" aria-label="주요 메뉴"><div class="bottom-nav-inner">${x.map(([i,p,t])=>`<a class="nav-item ${p===active?'active':''}" href="#/${p}">${I(i)}<span>${t}</span></a>`).join('')}</div></nav>`}
function wrap(html,o={}){return `${o.nohead?'':head(o.title||'낌새',o.back!==false)}<main id="main" class="page ${o.narrow?'narrow':''}" tabindex="-1">${html}${foot()}</main>${o.bottom?nav(o.care,o.active):''}`}
const notice=(h,p)=>`<div class="notice"><strong>${h}</strong>${p}</div>`;
const row=(h,s='',right=I('chevron-right'))=>`<div class="list-row"><span><strong>${h}</strong>${s?`<small>${s}</small>`:''}</span>${right}</div>`;
const page={};
page.start=()=>wrap(`<section class="hero"><img class="hero-logo" src="./assets/icons/icon.svg" alt="낌새 로고"><div class="eyebrow">오늘도, 변화를 먼저 알아차리는</div><h1>낌새</h1><p>작은 관심이 큰 안심이 됩니다.<br>나와 가족의 인지·생활 변화를 쉽고 꾸준하게 기록해요.</p><div class="hero-actions">${btn('시작하기','role')}${btn('로그인','auth','btn-secondary-k')}</div></section>${notice('접근성을 기본으로 설계했어요.','큰 글씨, 큰 터치 영역, 색상+아이콘, 화면 읽기와 음성 안내를 지원합니다.')}`,{nohead:true,narrow:true});
page.role=()=>wrap(`<div class="eyebrow">가입 1/3</div><h1 class="page-title">어떤 목적으로 사용하시나요?</h1><p class="page-desc">역할은 나중에 언제든 추가할 수 있어요.</p>${[['self','👵','제가 사용해요','내 건강을 스스로 관리해요.','bg-blue'],['care','👩','가족을 돌보고 있어요','가족의 상태를 함께 살펴봐요.','bg-pink'],['both','👵👩','둘 다 사용해요','내 건강도 챙기고 가족도 돌봐요.','bg-purple']].map(x=>`<button class="role-card ${x[4]}" data-role="${x[0]}"><span class="avatar-lg">${x[1]}</span><span><h3>${x[2]}</h3><p>${x[3]}</p></span>${I('chevron-right')}</button>`).join('')}${notice('계정은 하나, 역할은 여러 개.','보호자로 시작해도 나중에 사용자 역할을 추가할 수 있어요.')}`,{title:'역할 선택',narrow:true});
page.auth=()=>wrap(`<div class="eyebrow">가입 2/3</div><h1 class="page-title">간편하게 시작하세요</h1><div class="form-stack"><div class="field"><label for="name">이름</label><input id="name" value="${S.account?.name||''}" placeholder="이름"></div><div class="field"><label for="email">이메일</label><input id="email" type="email" value="${S.account?.email||''}" placeholder="name@example.com"></div><button id="signup" class="btn-kimse btn-primary-k">이메일로 시작하기</button></div>`,{title:'회원가입 / 로그인',narrow:true});
page.account=()=>{demo();return wrap(`<h1 class="page-title">내 계정 / 역할 관리</h1><div class="summary-card"><h3>${S.account.name}님</h3><p>${S.account.email}</p></div><div class="list">${row('사용자','내 건강을 관리하는 역할',`<span class="context-chip">${S.self?'활성':'미등록'}</span>`)}${row('보호자','가족을 돌보는 역할',`<span class="context-chip caregiver">${S.care?'활성':'미등록'}</span>`)}</div><div class="hero-actions"><button class="btn-kimse btn-blue-k" data-add-role="self">+ 사용자 역할 추가</button><button class="btn-kimse btn-secondary-k" data-add-role="care">+ 보호자 역할 추가</button>${btn('역할 전환','switch')}</div>`,{title:'내 계정',narrow:true})};
page.switch=()=>{demo();return wrap(`<h1 class="page-title">어떤 화면으로 이동할까요?</h1>${S.self?`<button class="role-card bg-blue" data-mode="self"><span class="avatar-lg">👵</span><span><h3>사용자 화면</h3><p>내 건강을 관리해요.</p></span>${I('chevron-right')}</button>`:''}${S.care?`<button class="role-card bg-pink" data-mode="care"><span class="avatar-lg">👩</span><span><h3>보호자 화면</h3><p>가족을 돌봐요.</p></span>${I('chevron-right')}</button>`:''}${!S.care?notice('보호자 역할이 아직 없어요.','내 계정에서 언제든 추가할 수 있어요.'):''}`,{title:'역할 전환',narrow:true})};
page.home=()=>{demo();return wrap(`<div class="d-flex justify-content-between"><div><span class="context-chip">내 건강 보기</span><h1 class="page-title">안녕하세요<br>${S.account.name}님</h1></div><button class="icon-button" data-go="switch" aria-label="역할 전환">${I('switch-horizontal')}</button></div><div class="summary-card bg-amber"><h3>오늘도 좋은 하루예요.</h3><p>오늘의 인지 체크를 천천히 시작해보세요.</p></div><div class="card-grid">${[['🧠','오늘의 인지 체크','assessment-start','bg-pink'],['🧩','인지 훈련','training','bg-purple'],['💊','복약 관리','medication','bg-amber'],['💚','건강 기록','health','bg-mint']].map(x=>`<a class="action-card ${x[3]}" href="#/${x[2]}"><span class="icon">${x[0]}</span><strong>${x[1]}</strong></a>`).join('')}</div><h2 class="section-title">가족과 함께</h2><a href="#/family" class="list-row"><span><strong>${S.caregivers.length?`연결된 보호자 ${S.caregivers.length}명`:'가족/보호자 연결하기'}</strong><small>첫 보호자/비상 알림 수신자 1인은 무료예요.</small></span>${I('chevron-right')}</a>`,{back:false,bottom:true,active:'home'})};
page['assessment-start']=()=>wrap(`<div class="eyebrow">오늘의 인지 체크</div><h1 class="page-title">지금, 나의 상태를 확인해요</h1>${row('예상 시간','약 3분','3분')}${row('문항','기억·집중·언어','3문항')}${notice('검사 결과만으로 치매 여부를 판단하지 않습니다.','평소와 비교한 변화 관찰을 돕기 위한 체크입니다.')}<button id="begin" class="btn-kimse btn-primary-k btn-full">시작하기</button>`,{title:'인지 체크 시작',narrow:true});
const Q=[['방금 본 물건 중 사과는 무엇인가요?',['🍎 사과','🍌 바나나','☕ 컵','🐶 강아지'],0],['오늘은 몇 월인가요?',['1월','4월','7월','9월'],3],['같은 그림을 골라보세요.',['🐶 강아지','🐱 고양이','🐰 토끼','🐿️ 다람쥐'],0]];
page.assessment=()=>{let i=Math.min(S.q,Q.length-1),q=Q[i];return wrap(`<strong>인지 체크 ${i+1}/${Q.length}</strong><div class="progress-k mt-2"><span style="width:${(i+1)/Q.length*100}%"></span></div><h1 class="page-title mt-4">${q[0]}</h1><div class="answer-grid">${q[1].map((x,j)=>`<button class="answer" data-answer="${j}" aria-pressed="${S.answers[i]===j}">${x}</button>`).join('')}</div><button id="next" class="btn-kimse btn-primary-k btn-full" ${S.answers[i]===undefined?'disabled':''}>${i===Q.length-1?'결과 보기':'다음 문제'}</button>`,{title:'인지 체크',narrow:true})};
page.result=()=>{let score=Math.round((S.answers.filter((v,i)=>v===Q[i]?.[2]).length/Q.length)*100);return wrap(`<div class="eyebrow">인지 체크 결과</div><h1 class="page-title">수고하셨어요!</h1><div class="summary-card text-center"><div class="context-chip">종합 점수</div><div style="font-size:64px;font-weight:900;color:#14755f">${score}<small style="font-size:22px">점</small></div><strong>지금도 충분히 잘하고 계세요.</strong></div>${notice('변화 관찰용 결과입니다.','점수만으로 치매 여부를 판단하지 않으며 지속적인 변화가 있으면 전문가 상담을 권합니다.')}${btn('홈으로','home')}`,{title:'인지 결과',narrow:true})};
page.training=()=>wrap(`<h1 class="page-title">인지 훈련</h1><p class="page-desc">즐겁게, 꾸준히 뇌를 건강하게.</p><div class="list">${row('🖼️ 기억 훈련','그림과 단어를 기억해요')}${row('🎯 집중 훈련','다른 그림을 찾아요')}${row('💬 언어 훈련','낱말을 완성해요')}${row('☕ 일상 훈련','생활 문제를 풀어요')}</div>`,{title:'인지 훈련',bottom:true,active:'training'});
page.medication=()=>wrap(`<h1 class="page-title">복약 관리</h1>${row('혈압약','오전 08:00',`<button class="btn-kimse ${S.med?'btn-secondary-k':'btn-primary-k'}" data-med>${S.med?'완료 ✓':'복용'}</button>`)}${row('비타민','오후 12:00','복용 전')}${btn('+ 약 등록하기','medication','btn-blue-k')}`,{title:'복약 관리',narrow:true});
page.health=()=>wrap(`<h1 class="page-title">건강 기록</h1><div class="summary-card"><h3>오늘의 기분</h3><div class="answer-grid" style="grid-template-columns:repeat(3,1fr)">${[['🙂','좋아요'],['😐','보통이에요'],['🙁','안 좋아요']].map(x=>`<button class="answer" data-mood="${x[1]}" aria-pressed="${S.mood===x[1]}"><span class="emoji">${x[0]}</span>${x[1]}</button>`).join('')}</div></div>${row('🌙 수면','지난밤','7시간 30분')}${row('🚶 활동량','오늘','4,320 걸음')}${row('❤️ 혈압','최근','120 / 80')}`,{title:'건강 기록',bottom:true,active:'health'});
page['caregiver-home']=()=>{demo();return wrap(`<span class="context-chip caregiver">가족 돌봄 보기</span><h1 class="page-title">안녕하세요<br>${S.account.name}님</h1><div class="summary-card bg-pink"><h3>연결된 가족</h3><p>가족의 오늘 상태를 한눈에 확인하세요.</p></div><div class="card-grid">${[['📊','상태 요약','report'],['🚨','비상 알림','emergency'],['📅','일정 관리','health'],['👨‍👩‍👧','가족 관리','family']].map(x=>`<a class="action-card" href="#/${x[2]}"><span class="icon">${x[0]}</span><strong>${x[1]}</strong></a>`).join('')}</div><h2 class="section-title">내 기능도 사용하기</h2><button class="btn-kimse btn-blue-k btn-full" data-add-role="self">내 건강 관리 사용자 역할 추가/이동</button>`,{back:false,bottom:true,care:true,active:'caregiver-home'})};
page.family=()=>wrap(`<h1 class="page-title">가족 연결 관리</h1><div class="summary-card bg-blue"><h3>보호자 ${S.caregivers.length}명 연결</h3><p>첫 보호자 1인은 무료, 두 번째 활성 연결부터 구독이 필요해요.</p></div><div class="list">${S.caregivers.map((x,i)=>row(x.name,i?'자녀':'배우자','연결됨')).join('')||'<div class="empty-state"><h3>연결된 보호자가 없어요</h3></div>'}</div><button id="add-family" class="btn-kimse btn-primary-k btn-full mt-3">+ 보호자 추가하기</button>`,{title:'가족 연결 관리',narrow:true});
page.report=()=>wrap(`<h1 class="page-title">상태 리포트</h1><div class="summary-card"><h3>최근 7일 변화</h3>${row('🧠 인지 점수','','↑ 3')}${row('🌙 수면','평균','6시간 30분')}${row('🚶 활동량','','↑ 12%')}${row('💊 복약 준수','','86%')}</div>${notice('지속되는 변화가 걱정된다면','의료기관 상담을 권합니다. 낌새는 진단을 대신하지 않습니다.')}`,{title:'상태 리포트',narrow:true});
page.emergency=()=>wrap(`<h1 class="page-title">비상 알림</h1><div class="summary-card bg-pink text-center"><div style="font-size:58px">🚨</div><h2>비상 알림</h2><p>사용자가 긴급 도움을 요청하면 연결된 가족에게 알림을 전달합니다.</p></div>${row('알림 수신자','','연결된 보호자')}${row('현재 상태','','알림 대기')}${notice('가족 연결','비상상태는 등록된 보호자에게 전달되도록 설계되어 있습니다.')}`,{title:'비상 알림',narrow:true});
page.market=()=>wrap(`<h1 class="page-title">치매 케어관</h1><p class="page-desc">제품·서비스 파트너를 분리된 공간에서 살펴보세요.</p>${notice('입점/광고 콘텐츠는 명확하게 표시합니다.','낌새가 특정 제품의 치료·예방 효과를 보증하지 않습니다.')}<div class="market-grid">${[['💊','제약'],['🧠','교육 / 인지훈련'],['🩺','의료기기'],['🛍️','생활제품'],['📱','앱 / 웹 서비스'],['🤝','전문 서비스']].map(x=>`<div class="market-card"><div style="font-size:34px">${x[0]}</div><h3>${x[1]}</h3><span class="sponsored">입점 카테고리</span></div>`).join('')}</div>`,{title:'치매 케어관',narrow:true});
page.plan=()=>wrap(`<h1 class="page-title">구독 플랜</h1><div class="plan-grid"><div class="plan"><h3>기본 무료</h3><div class="price">0원</div><p>보호자/비상 알림 1인 포함</p></div><div class="plan featured"><h3>프리미엄</h3><div class="price">가족 확장</div><p>보호자 2인 이상, 가족 다중 알림, 상세 리포트</p><button id="premium" class="btn-kimse btn-primary-k btn-full">보호자 2인 이상 사용</button></div></div>${notice('실제 가격은 아직 확정하지 않았습니다.','결제사와 가격을 임의로 만들지 않습니다.')}`,{title:'구독 플랜'});
page.accessibility=()=>{let R=[['largeText','글자 크게 보기'],['highContrast','고대비 모드'],['voiceGuidance','음성 안내'],['captions','자막 / 텍스트 대체'],['largeTouchTargets','큰 터치 영역'],['colorIcons','색상 + 아이콘 병행'],['screenReader','화면 읽기 지원'],['reduceMotion','동작 최소화']];return wrap(`<h1 class="page-title">접근성 설정</h1><p class="page-desc">고령층·저시력/시각장애·청각장애·색각 이상·운동장애를 기본 범위로 지원합니다.</p><div class="summary-card">${R.map(([k,t])=>`<div class="switch-row"><label for="a-${k}">${t}</label><input id="a-${k}" class="switch" type="checkbox" data-a11y="${k}" ${S.a11y[k]?'checked':''}></div>`).join('')}</div>${notice('시청각 동시중복장애','촉각/모스 인터페이스는 후속 단계로 분리했습니다.')}`,{title:'접근성 설정',narrow:true})};
page.settings=()=>{demo();return wrap(`<h1 class="page-title">설정</h1><div class="summary-card"><h3>${S.account.name}</h3><p>${S.account.email}</p></div><div class="list"><a class="list-row" href="#/account">내 프로필 / 역할 관리 ${I('chevron-right')}</a><a class="list-row" href="#/family">가족 / 보호자 관리 ${I('chevron-right')}</a><a class="list-row" href="#/accessibility">접근성 설정 ${I('chevron-right')}</a><a class="list-row" href="#/plan">구독 관리 ${I('chevron-right')}</a><a class="list-row" href="#/market">치매 케어관 ${I('chevron-right')}</a><a class="list-row" href="../" target="_blank">연구 근거 / Evidence ${I('external-link')}</a></div>`,{title:'설정',narrow:true})};
function applyA11y(){document.documentElement.classList.toggle('large-text',S.a11y.largeText);document.documentElement.classList.toggle('large-touch',S.a11y.largeTouchTargets);document.documentElement.classList.toggle('high-contrast',S.a11y.highContrast)}
function render(){applyA11y();let r=route(),f=page[r]||page.start;A.innerHTML=f();setTimeout(()=>$('#main')?.focus({preventScroll:true}),0);document.title='낌새 · '+r}
document.addEventListener('click',e=>{let t=e.target.closest('[data-go],[data-back],[data-role],[data-mode],[data-add-role],[data-answer],[data-med],[data-mood]');if(!t)return;if(t.dataset.go)go(t.dataset.go);if(t.hasAttribute('data-back'))history.length>1?history.back():go('start');if(t.dataset.role){S.intent=t.dataset.role;S.self=['self','both'].includes(S.intent);S.care=['care','both'].includes(S.intent);save();go('auth')}if(t.dataset.mode){S.mode=t.dataset.mode;save();go(S.mode==='care'?'caregiver-home':'home')}if(t.dataset.addRole){S[t.dataset.addRole]=true;S.mode=t.dataset.addRole==='care'?'care':'self';save();go(S.mode==='care'?'caregiver-home':'home')}if(t.dataset.answer!==undefined){S.answers[S.q]=+t.dataset.answer;save();render()}if(t.hasAttribute('data-med')){S.med=!S.med;save();render()}if(t.dataset.mood){S.mood=t.dataset.mood;save();render()}});
document.addEventListener('change',e=>{if(e.target.dataset.a11y){S.a11y[e.target.dataset.a11y]=e.target.checked;save();render();say(e.target.closest('.switch-row').innerText+(e.target.checked?' 켰습니다':' 껐습니다'))}});
document.addEventListener('click',e=>{if(e.target.id==='signup'){S.account={name:$('#name').value.trim()||'김○○',email:$('#email').value.trim()||'kimse@example.com'};S.mode=S.intent==='care'?'care':'self';save();go(S.mode==='care'?'caregiver-home':'home')}if(e.target.id==='begin'){S.q=0;S.answers=[];save();go('assessment')}if(e.target.id==='next'){if(S.answers[S.q]===undefined)return;if(S.q>=Q.length-1)go('result');else{S.q++;save();render()}}if(e.target.id==='add-family'){if(S.caregivers.length>=1&&S.plan!=='PREMIUM'){say('두 번째 보호자부터 구독이 필요합니다.');go('plan')}else{S.caregivers.push({name:`보호자 ${S.caregivers.length+1}`});save();render()}}if(e.target.id==='premium'){S.plan='PREMIUM';save();say('가족 확장 기능이 적용되었습니다.');go('family')}});
window.addEventListener('hashchange',render);window.addEventListener('online',()=>{O.hidden=true;say('인터넷 연결이 복구되었습니다.')});window.addEventListener('offline',()=>{O.hidden=false;say('인터넷 연결이 끊겼습니다.')});O.hidden=navigator.onLine;render();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();