(()=>{'use strict';
const $=s=>document.querySelector(s),A=$('#app'),N=$('#announcer'),O=$('#offline-banner'),K='kimse.p0.state',MODEL_CACHE='kimse.evidence.model.cache';
const D={account:null,intent:null,self:false,care:false,mode:'self',caregivers:[],alertRecipients:[],plan:'FREE',q:0,answers:[],med:false,mood:'좋아요',
  medicines:[{id:'bp',name:'혈압약',time:'08:00',note:'아침 식사 후',taken:false},{id:'vitamin',name:'비타민',time:'12:00',note:'점심 식사 후',taken:false}],
  health:{sleep:'7시간 30분',steps:'4,320 걸음',pressure:'120 / 80',memo:''},
  schedule:[{id:'s1',date:'오늘 19:00',title:'저녁 복약 확인'},{id:'s2',date:'내일 10:30',title:'가족 안부 확인'}],
  selectedTraining:'memory',trainingResult:null,selectedHealth:'sleep',marketCategory:'all',marketItem:null,marketFavorites:[],partnerStatus:null,
  a11y:{largeText:false,highContrast:false,voiceGuidance:false,soundEffects:false,captions:true,largeTouchTargets:true,colorIcons:true,screenReader:true,reduceMotion:false}};
const stored=JSON.parse(localStorage.getItem(K)||'{}');
let S=Object.assign(structuredClone(D),stored);
S.a11y=Object.assign({},D.a11y,stored.a11y||{});
if(!Array.isArray(S.medicines))S.medicines=structuredClone(D.medicines);
if(!S.health||typeof S.health!=='object')S.health=structuredClone(D.health);
if(!Array.isArray(S.schedule))S.schedule=structuredClone(D.schedule);
if(!Array.isArray(S.marketFavorites))S.marketFavorites=[];
const save=()=>{localStorage.setItem(K,JSON.stringify(S));applyA11y()},go=p=>location.hash='#/'+p,route=()=>(location.hash||'#/start').slice(2).split('?')[0],evidenceUrl=()=>/\/app(?:\/|$)/.test(location.pathname)?'../evidence/':'./evidence/';
const evidenceModelUrls=()=>/\/app(?:\/|$)/.test(location.pathname)?['../evidence/evidence-model.json','../evidence-model.json']:['./evidence/evidence-model.json','./evidence-model.json'];
let EVIDENCE_MODEL=null,Q=[];
const validModel=m=>m&&m.activeModel&&Array.isArray(m.activeModel.factors)&&m.activeModel.factors.length>0;
async function loadEvidenceModel(){
  for(const url of evidenceModelUrls()){
    try{
      const r=await fetch(url,{cache:'no-store'});
      if(!r.ok)continue;
      const m=await r.json();
      if(!validModel(m))continue;
      EVIDENCE_MODEL=m;
      localStorage.setItem(MODEL_CACHE,JSON.stringify(m));
      break;
    }catch{}
  }
  if(!EVIDENCE_MODEL){
    try{const cached=JSON.parse(localStorage.getItem(MODEL_CACHE)||'null');if(validModel(cached))EVIDENCE_MODEL=cached}catch{}
  }
  Q=(EVIDENCE_MODEL?.activeModel?.factors||[]).map(f=>({factorId:f.id,label:f.label,question:f.question,options:f.options||[],evidence:f.evidence}));
  return !!EVIDENCE_MODEL;
}
const assessmentScore=()=>Q.reduce((sum,q,i)=>{const o=q.options[S.answers[i]];return sum+(o?Number(o.points)||0:0)},0);
const API='https://api-kimse.suaveforge.com';
let audioCtx=null,lastSpokenRoute='';
const tone=(kind='tap')=>{if(!S.a11y.soundEffects)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();const hz=kind==='success'?660:kind==='warning'?260:440;o.frequency.value=hz;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.07,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.12);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}catch{}};
const say=t=>{N.textContent='';setTimeout(()=>N.textContent=t,10);if(S.a11y.voiceGuidance&&'speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='ko-KR';u.rate=.9;speechSynthesis.speak(u)}};
const feedback=(t,kind='tap')=>{tone(kind);say(t)};
const I=n=>`<i class="ti ti-${n}" aria-hidden="true"></i>`,btn=(t,p,c='btn-primary-k')=>`<button class="btn-kimse ${c} btn-full" data-go="${p}">${t}</button>`;
function demo(){if(S.account)return;S.account={name:'김○○',email:'kimse@example.com'};S.self=true;save()}
function head(t='낌새',back=true){return `<header class="app-header"><div class="app-header-inner">${back?`<button class="icon-button" data-back aria-label="이전 화면">${I('chevron-left')}</button>`:`<a class="brand" href="#/home"><span class="brand-mark" aria-hidden="true">낌</span><span>낌새<small class="brand-sub">작은 변화를 먼저 알아차려요</small></span></a>`}<strong>${back?t:''}</strong><a class="icon-button" href="#/settings" aria-label="설정">${I('settings')}</a></div></header>`}
const foot=()=>`<div class="app-footer">Updated 2026.09.14 · Release 06<br>의료 진단을 대신하지 않으며 변화 관찰과 기록을 돕습니다.</div>`;
function nav(care=false,active=route()){let x=care?[['home','caregiver-home','홈'],['bell','emergency','알림'],['users','family','가족'],['chart-line','report','리포트'],['dots','settings','더보기']]:[['home','home','홈'],['checkbox','assessment-start','체크'],['barbell','training','훈련'],['clipboard-heart','health','기록'],['dots','settings','더보기']];return `<nav class="bottom-nav" aria-label="주요 메뉴"><div class="bottom-nav-inner">${x.map(([i,p,t])=>`<a class="nav-item ${p===active?'active':''}" href="#/${p}">${I(i)}<span>${t}</span></a>`).join('')}</div></nav>`}
function wrap(html,o={}){return `${o.nohead?'':head(o.title||'낌새',o.back!==false)}<main id="main" class="page ${o.narrow?'narrow':''}" tabindex="-1">${html}${foot()}</main>${o.bottom?nav(o.care,o.active):''}`}
const notice=(h,p)=>`<div class="notice"><strong>${h}</strong>${p}</div>`;
const row=(h,s='',right='')=>`<div class="list-row"><span><strong>${h}</strong>${s?`<small>${s}</small>`:''}</span>${right}</div>`;
const page={};
page.start=()=>wrap(`<section class="hero"><img class="hero-logo" src="./assets/icons/icon.svg" alt="낌새 로고"><div class="eyebrow">오늘도, 변화를 먼저 알아차리는</div><h1>낌새</h1><p>작은 관심이 큰 안심이 됩니다.<br>나와 가족의 인지·생활 변화를 쉽고 꾸준하게 기록해요.</p><div class="hero-actions">${btn('시작하기','role')}${btn('로그인','auth','btn-secondary-k')}</div></section>${notice('접근성을 기본으로 설계했어요.','큰 글씨, 큰 터치 영역, 색상+아이콘, 화면 읽기와 음성 안내를 지원합니다.')}`,{nohead:true,narrow:true});
page.role=()=>wrap(`<div class="eyebrow">가입 1/3</div><h1 class="page-title">어떤 목적으로 사용하시나요?</h1><p class="page-desc">역할은 나중에 언제든 추가할 수 있어요.</p>${[['self','👵','제가 사용해요','내 건강을 스스로 관리해요.','bg-blue'],['care','👩','가족을 돌보고 있어요','가족의 상태를 함께 살펴봐요.','bg-pink'],['both','👵👩','둘 다 사용해요','내 건강도 챙기고 가족도 돌봐요.','bg-purple']].map(x=>`<button class="role-card ${x[4]}" data-role="${x[0]}"><span class="avatar-lg">${x[1]}</span><span><h3>${x[2]}</h3><p>${x[3]}</p></span>${I('chevron-right')}</button>`).join('')}${notice('계정은 하나, 역할은 여러 개.','보호자로 시작해도 나중에 사용자 역할을 추가할 수 있어요.')}`,{title:'역할 선택',narrow:true});
page.auth=()=>wrap(`<div class="eyebrow">가입 2/3</div><h1 class="page-title">간편하게 시작하세요</h1><div class="form-stack"><div class="field"><label for="name">이름</label><input id="name" value="${S.account?.name||''}" placeholder="이름"></div><div class="field"><label for="email">이메일</label><input id="email" type="email" value="${S.account?.email||''}" placeholder="name@example.com"></div><button id="signup" class="btn-kimse btn-primary-k">이메일로 시작하기</button></div>`,{title:'회원가입 / 로그인',narrow:true});
page.account=()=>{demo();return wrap(`<h1 class="page-title">내 계정 / 역할 관리</h1><div class="summary-card"><h3>${S.account.name}님</h3><p>${S.account.email}</p></div><div class="list">${row('사용자','내 건강을 관리하는 역할',`<span class="context-chip">${S.self?'활성':'미등록'}</span>`)}${row('보호자','가족을 돌보는 역할',`<span class="context-chip caregiver">${S.care?'활성':'미등록'}</span>`)}</div><div class="hero-actions"><button class="btn-kimse btn-blue-k" data-add-role="self">+ 사용자 역할 추가</button><button class="btn-kimse btn-secondary-k" data-add-role="care">+ 보호자 역할 추가</button>${btn('역할 전환','switch')}</div>`,{title:'내 계정',narrow:true})};
page.switch=()=>{demo();return wrap(`<h1 class="page-title">어떤 화면으로 이동할까요?</h1>${S.self?`<button class="role-card bg-blue" data-mode="self"><span class="avatar-lg">👵</span><span><h3>사용자 화면</h3><p>내 건강을 관리해요.</p></span>${I('chevron-right')}</button>`:''}${S.care?`<button class="role-card bg-pink" data-mode="care"><span class="avatar-lg">👩</span><span><h3>보호자 화면</h3><p>가족을 돌봐요.</p></span>${I('chevron-right')}</button>`:''}${!S.care?notice('보호자 역할이 아직 없어요.','내 계정에서 언제든 추가할 수 있어요.'):''}`,{title:'역할 전환',narrow:true})};
page.home=()=>{demo();return wrap(`<div class="d-flex justify-content-between"><div><span class="context-chip">내 건강 보기</span><h1 class="page-title">안녕하세요<br>${S.account.name}님</h1></div><button class="icon-button" data-go="switch" aria-label="역할 전환">${I('switch-horizontal')}</button></div><div class="summary-card bg-amber"><h3>오늘도 좋은 하루예요.</h3><p>근거 기반 위험요인 체크를 천천히 시작해보세요.</p></div><div class="card-grid">${[['🧠','근거 기반 체크','assessment-start','bg-pink'],['🧩','인지 훈련','training','bg-purple'],['💊','복약 관리','medication','bg-amber'],['💚','건강 기록','health','bg-mint']].map(x=>`<a class="action-card ${x[3]}" href="#/${x[2]}"><span class="icon">${x[0]}</span><strong>${x[1]}</strong></a>`).join('')}</div><h2 class="section-title">가족과 함께</h2><a href="#/family" class="list-row"><span><strong>${S.caregivers.length?`연결된 보호자 ${S.caregivers.length}명`:'가족/보호자 연결하기'}</strong><small>가족/보호자 연결은 구독과 별개로 관리할 수 있어요.</small></span>${I('chevron-right')}</a>`,{back:false,bottom:true,active:'home'})};
page['assessment-start']=()=>{const a=EVIDENCE_MODEL?.activeModel;if(!a)return wrap(`<h1 class="page-title">근거 모델을 불러오지 못했습니다</h1>${notice('점수를 추정하지 않습니다.','근거 레지스트리를 다시 불러온 뒤 이용해주세요.')}`,{title:'근거 기반 체크',narrow:true});return wrap(`<div class="eyebrow">근거 기반 위험요인 체크</div><h1 class="page-title">${a.name}</h1>${row('팩터',a.factors.map(f=>f.label).join(' · '),a.factors.length+'개')}${row('조합',a.combination.rule,'최대 '+a.combination.maxScore+'점')}${notice('공개 검증된 원 점수체계를 사용합니다.','이 점수는 장기 위험요인 연구모델이며 치매 진단이나 현재 인지상태 판정이 아닙니다.')}<button id="begin" class="btn-kimse btn-primary-k btn-full">시작하기</button>`,{title:'근거 기반 체크',narrow:true})};
page.assessment=()=>{if(!Q.length)return page['assessment-start']();let i=Math.min(S.q,Q.length-1),q=Q[i];return wrap(`<strong>위험요인 체크 ${i+1}/${Q.length}</strong><div class="progress-k mt-2"><span style="width:${(i+1)/Q.length*100}%"></span></div><div class="eyebrow mt-4">${q.label} · ${q.evidence}</div><h1 class="page-title">${q.question}</h1><div class="answer-grid">${q.options.map((x,j)=>`<button class="answer" data-answer="${j}" aria-pressed="${S.answers[i]===j}">${x.label}<small>${x.points}점</small></button>`).join('')}</div><button id="next" class="btn-kimse btn-primary-k btn-full" ${S.answers[i]===undefined?'disabled':''}>${i===Q.length-1?'결과 보기':'다음'}</button>`,{title:'근거 기반 체크',narrow:true})};
page.result=()=>{const a=EVIDENCE_MODEL?.activeModel;if(!a||!Q.length)return page['assessment-start']();const score=assessmentScore(),max=a.combination.maxScore,cut=a.combination.researchCutoff;const rows=Q.map((q,i)=>{const o=q.options[S.answers[i]];return row(q.label,o?o.label:'미응답',o?o.points+'점':'-')}).join('');return wrap(`<div class="eyebrow">근거 기반 체크 결과</div><h1 class="page-title">${a.name}</h1><div class="summary-card text-center"><div class="context-chip">공개 원 점수 합계</div><div style="font-size:64px;font-weight:900;color:#14755f">${score}<small style="font-size:22px"> / ${max}</small></div><strong>7개 CAIDE Model 1 팩터의 원 점수 합산</strong></div><div class="list">${rows}</div>${notice('원 연구의 참고 기준: '+cut.operator+cut.value+'점',cut.note)}${notice('해석 범위','CAIDE는 중년기의 장기 치매 위험 연구모델입니다. 현재 인지상태나 치매 여부를 이 점수로 판정하지 않습니다.')}${btn('홈으로','home')}`,{title:'근거 기반 결과',narrow:true})};
const TRAINING={
memory:{icon:'🖼️',title:'기억 훈련',desc:'짧게 보고 핵심 정보를 떠올려요.',prompt:'조금 전 본 세 단어 중 포함된 것은?',choices:['사과','기차','연필','우산'],correct:0,hint:'정답보다 꾸준한 회상이 중요해요.'},
attention:{icon:'🎯',title:'집중 훈련',desc:'비슷한 것 사이에서 다른 하나를 찾아요.',prompt:'다른 하나를 골라보세요.',choices:['● ● ●','● ● ●','● ○ ●','● ● ●'],correct:2,hint:'서두르지 말고 한 줄씩 살펴보세요.'},
language:{icon:'💬',title:'언어 훈련',desc:'말의 뜻과 연결을 천천히 떠올려요.',prompt:'“따뜻하다”와 가장 가까운 말은?',choices:['포근하다','무겁다','빠르다','멀다'],correct:0,hint:'평소 쓰는 쉬운 말부터 연결해요.'},
daily:{icon:'☕',title:'일상 훈련',desc:'생활 속 순서와 판단을 연습해요.',prompt:'외출 전에 가장 먼저 확인하면 좋은 것은?',choices:['가스·문 잠금','TV 채널','사진 정리','서랍 색상'],correct:0,hint:'실제 생활과 연결해 반복하는 훈련이에요.'}
};
page.training=()=>wrap(`<h1 class="page-title">인지 훈련</h1><p class="page-desc">메뉴만 있는 화면이 아니라 바로 실행할 수 있는 짧은 훈련으로 구성했어요.</p><div class="list">${Object.entries(TRAINING).map(([k,x])=>`<button class="list-row menu-row" data-training="${k}"><span><strong>${x.icon} ${x.title}</strong><small>${x.desc}</small></span>${I('chevron-right')}</button>`).join('')}</div>${notice('훈련은 진단이 아닙니다.','정답률보다 규칙적인 참여와 변화 추이를 살펴보는 용도입니다.')}`,{title:'인지 훈련',bottom:true,active:'training'});
page['training-play']=()=>{const x=TRAINING[S.selectedTraining]||TRAINING.memory;const done=S.trainingResult&&S.trainingResult.type===S.selectedTraining;return wrap(`<div class="eyebrow">${x.icon} ${x.title}</div><h1 class="page-title">${x.prompt}</h1><p class="page-desc">${x.desc}</p><div class="answer-grid">${x.choices.map((c,i)=>`<button class="answer" data-training-answer="${i}" ${done?'disabled':''}>${c}</button>`).join('')}</div>${done?notice(S.trainingResult.correct?'잘했어요.':'괜찮아요. 다시 떠올려보세요.',x.hint):''}${done?'<button class="btn-kimse btn-secondary-k btn-full" data-training-reset>한 번 더 하기</button>':''}`,{title:x.title,narrow:true})};
page.medication=()=>wrap(`<h1 class="page-title">복약 관리</h1><p class="page-desc">등록한 약마다 복용 여부를 바로 기록할 수 있어요.</p><div class="list">${S.medicines.map(m=>row('💊 '+m.name,`${m.time} · ${m.note||'복용 메모 없음'}`,`<button class="btn-kimse ${m.taken?'btn-secondary-k':'btn-primary-k'}" data-med-id="${m.id}">${m.taken?'복용 완료 ✓':'복용 기록'}</button>`)).join('')}</div><div class="hero-actions">${btn('+ 약 등록하기','medication-add','btn-blue-k')}</div>`,{title:'복약 관리',narrow:true});
page['medication-add']=()=>wrap(`<h1 class="page-title">약 등록</h1><div class="form-stack"><div class="field"><label for="med-name">약 이름</label><input id="med-name" placeholder="예: 혈압약"></div><div class="field"><label for="med-time">복용 시간</label><input id="med-time" type="time" value="08:00"></div><div class="field"><label for="med-note">복용 메모</label><input id="med-note" placeholder="예: 아침 식사 후"></div><button id="save-med" class="btn-kimse btn-primary-k">등록하기</button></div>`,{title:'약 등록',narrow:true});
const HEALTH_META={sleep:['🌙','수면','지난밤'],steps:['🚶','활동량','오늘'],pressure:['❤️','혈압','최근']};
page.health=()=>wrap(`<h1 class="page-title">건강 기록</h1><div class="summary-card"><h3>오늘의 기분</h3><div class="answer-grid" style="grid-template-columns:repeat(3,1fr)">${[['🙂','좋아요'],['😐','보통이에요'],['🙁','안 좋아요']].map(x=>`<button class="answer" data-mood="${x[1]}" aria-pressed="${S.mood===x[1]}"><span class="emoji">${x[0]}</span>${x[1]}</button>`).join('')}</div></div><div class="list">${Object.entries(HEALTH_META).map(([k,x])=>`<button class="list-row menu-row" data-health="${k}"><span><strong>${x[0]} ${x[1]}</strong><small>${x[2]}</small></span><span><strong>${S.health[k]}</strong> ${I('chevron-right')}</span></button>`).join('')}</div>`,{title:'건강 기록',bottom:true,active:'health'});
page['health-detail']=()=>{const k=S.selectedHealth in HEALTH_META?S.selectedHealth:'sleep',x=HEALTH_META[k];return wrap(`<div class="eyebrow">${x[0]} ${x[1]}</div><h1 class="page-title">${x[1]} 기록 수정</h1><div class="form-stack"><div class="field"><label for="health-value">${x[1]} 값</label><input id="health-value" value="${S.health[k]||''}" placeholder="${k==='sleep'?'예: 7시간 30분':k==='steps'?'예: 4,320 걸음':'예: 120 / 80'}"></div><div class="field"><label for="health-memo">메모</label><textarea id="health-memo" rows="4" placeholder="특이사항이 있으면 적어주세요.">${S.health.memo||''}</textarea></div><button id="save-health" class="btn-kimse btn-primary-k">저장하기</button></div>`,{title:x[1]+' 기록',narrow:true})};
page['caregiver-home']=()=>{demo();return wrap(`<span class="context-chip caregiver">가족 돌봄 보기</span><h1 class="page-title">안녕하세요<br>${S.account.name}님</h1><div class="summary-card bg-pink"><h3>연결된 가족</h3><p>가족의 오늘 상태를 한눈에 확인하세요.</p></div><div class="card-grid">${[['📊','상태 요약','report'],['🚨','비상 알림','emergency'],['📅','일정 관리','care-schedule'],['👨‍👩‍👧','가족 관리','family']].map(x=>`<a class="action-card" href="#/${x[2]}"><span class="icon">${x[0]}</span><strong>${x[1]}</strong></a>`).join('')}</div><h2 class="section-title">내 기능도 사용하기</h2><button class="btn-kimse btn-blue-k btn-full" data-add-role="self">내 건강 관리 사용자 역할 추가/이동</button>`,{back:false,bottom:true,care:true,active:'caregiver-home'})};
page['care-schedule']=()=>wrap(`<h1 class="page-title">가족 일정 관리</h1><p class="page-desc">복약·안부·진료 같은 가족 일정을 한곳에 적어둘 수 있어요.</p><div class="list">${S.schedule.map(x=>row('📅 '+x.title,x.date,'예정')).join('')}</div><h2 class="section-title">일정 추가</h2><div class="form-stack"><div class="field"><label for="schedule-title">일정</label><input id="schedule-title" placeholder="예: 병원 동행"></div><div class="field"><label for="schedule-date">날짜/시간</label><input id="schedule-date" placeholder="예: 9월 16일 10:30"></div><button id="add-schedule" class="btn-kimse btn-primary-k">일정 추가</button></div>`,{title:'일정 관리',narrow:true});
page.family=()=>wrap(`<h1 class="page-title">가족 연결 관리</h1><div class="summary-card bg-blue"><h3>보호자 ${S.caregivers.length}명 연결</h3><p>가족 연결과 역할 관리는 구독 여부와 관계없이 사용할 수 있어요.</p></div><div class="list">${S.caregivers.map((x,i)=>row(x.name,i?'자녀':'배우자','연결됨')).join('')||'<div class="empty-state"><h3>연결된 보호자가 없어요</h3></div>'}</div><button class="btn-kimse btn-primary-k btn-full mt-3" data-go="family-add">+ 보호자 추가하기</button>`,{title:'가족 연결 관리',narrow:true});
page['family-add']=()=>wrap(`<h1 class="page-title">보호자 연결 추가</h1><div class="form-stack"><div class="field"><label for="family-name">이름</label><input id="family-name" placeholder="예: 김○○"></div><div class="field"><label for="family-relation">관계</label><input id="family-relation" placeholder="예: 배우자, 자녀"></div><button id="save-family" class="btn-kimse btn-primary-k">연결 정보 저장</button></div>${notice('현재 공개 버전','실제 초대 링크/본인인증 연동 전까지는 이 기기에 연결 정보를 저장합니다.')}`,{title:'보호자 추가',narrow:true});
page.report=()=>wrap(`<h1 class="page-title">상태 리포트</h1><div class="summary-card"><h3>최근 7일 변화</h3>${row('🧠 인지 점수','','↑ 3')}${row('🌙 수면','평균','6시간 30분')}${row('🚶 활동량','','↑ 12%')}${row('💊 복약 준수','','86%')}</div>${notice('지속되는 변화가 걱정된다면','의료기관 상담을 권합니다. 낌새는 진단을 대신하지 않습니다.')}`,{title:'상태 리포트',narrow:true});
page.emergency=()=>wrap(`<h1 class="page-title">비상 알림</h1><div class="summary-card bg-pink"><h3>비상상태 알림 수신자 ${S.alertRecipients.length}명</h3><p>수신자 1인까지 무료이며, 2인째부터 구독이 적용됩니다.</p></div><div class="list">${S.alertRecipients.map((x,i)=>row(x.name,i?'추가 수신자':'무료 수신자','알림 받음')).join('')||'<div class="empty-state"><h3>등록된 비상알림 수신자가 없어요</h3></div>'}</div><button class="btn-kimse btn-primary-k btn-full mt-3" data-go="alert-add">+ 비상알림 수신자 추가</button>${notice('가족 연결과는 별개예요.','보호자 역할을 추가하는 것 자체에는 이 구독 제한을 적용하지 않습니다.')}`,{title:'비상 알림',narrow:true});
page['alert-add']=()=>wrap(`<h1 class="page-title">비상알림 수신자 추가</h1><div class="form-stack"><div class="field"><label for="alert-name">이름</label><input id="alert-name" placeholder="예: 김○○"></div><div class="field"><label for="alert-relation">관계</label><input id="alert-relation" placeholder="예: 자녀"></div><div class="field"><label for="alert-phone">연락처</label><input id="alert-phone" inputmode="tel" placeholder="010-0000-0000"></div><button id="save-alert" class="btn-kimse btn-primary-k">수신자 저장</button></div>`,{title:'비상알림 수신자',narrow:true});
const MARKET_CATS=[
['all','🧭','전체'],['cognitive','🧠','인지·활동'],['safety','🛡️','안전·생활'],['emergency','📍','위치·비상'],['med','💊','복약·건강'],['meal','🥣','식사·영양'],['sense','🔊','감각·소통'],['care','🤝','돌봄·동행'],['digital','📱','디지털']
];
const MARKET_ITEMS=[
{id:'v1',cat:'cognitive',icon:'🧠',vendor:'실비아헬스',title:'Silvia 인지건강 관리',desc:'중장년·어르신이 일상에서 뇌 건강 셀프체크와 인지건강 관리를 이용할 수 있는 서비스.',note:'외부 업체 정보 · 비제휴',url:'https://silviahealth.com/'},
{id:'v2',cat:'safety',icon:'🦯',vendor:'케어맥스',title:'실버 안전·이동 보조용품',desc:'보행보조차, 지팡이, 목욕의자·워커 등 고령자 생활·이동 보조용품을 판매하는 실버용품 전문몰.',note:'외부 업체 정보 · 비제휴',url:'https://caremax.kr/'},
{id:'v3',cat:'emergency',icon:'📍',vendor:'국민건강보험공단 / 치매안심센터',title:'배회감지기·실종예방 지원',desc:'장기요양 수급자의 GPS형·매트형 배회감지기 대여와 치매안심센터 실종예방 서비스를 확인할 수 있어요.',note:'공공지원 정보',url:'https://www.longtermcare.or.kr/'},
{id:'v4',cat:'med',icon:'🩺',vendor:'한국오므론헬스케어',title:'가정용 혈압·건강 측정기기',desc:'자동전자혈압계와 앱 연동형 건강 측정기기를 제공하는 헬스케어 기기 업체.',note:'외부 업체 정보 · 비제휴',url:'https://www.omron-healthcare.co.kr/'},
{id:'v5',cat:'meal',icon:'🥤',vendor:'대상웰라이프',title:'뉴케어 균형영양식',desc:'식사가 어렵거나 균형 잡힌 영양 보충이 필요한 상황을 위한 환자용·균형영양식 브랜드.',note:'외부 업체 정보 · 비제휴',url:'https://www.daesangwellife.com/kr/brand/nucare-balanced-nutrition'},
{id:'v6',cat:'sense',icon:'👂',vendor:'시그니아',title:'보청기·청각 지원 솔루션',desc:'보청기, 액세서리, 앱·텔레케어 기능을 포함한 청각 지원 솔루션.',note:'외부 업체 정보 · 비제휴',url:'https://www.signia.net/ko-kr/'},
{id:'v7',cat:'care',icon:'🏠',vendor:'케어링',title:'방문요양·가족요양·주간보호',desc:'장기요양등급 상담부터 방문요양, 가족요양, 주간보호 등 재가 돌봄 서비스를 제공.',note:'외부 업체 정보 · 비제휴',url:'https://caring.co.kr/'},
{id:'v8',cat:'care',icon:'🤝',vendor:'케어닥',title:'간병·돌봄 서비스',desc:'병원 간병, 방문요양 등 보호자와 돌봄 인력을 연결하는 시니어 돌봄 서비스.',note:'외부 업체 정보 · 비제휴',url:'https://caredoc.kr/'},
{id:'v9',cat:'care',icon:'🚕',vendor:'케어네이션',title:'간병·병원동행·가사돌봄',desc:'병원·가정 간병과 병원동행, 가사돌봄, 방문요양 등을 연결하는 돌봄 플랫폼.',note:'외부 업체 정보 · 비제휴',url:'https://www.carenation.kr/'},
{id:'v10',cat:'digital',icon:'📱',vendor:'케어네이션',title:'보호자용 돌봄 앱',desc:'간병인 찾기, 동행, 복약 정보·알림, 병원·약국 찾기 등을 한 앱에서 제공.',note:'외부 업체 정보 · 비제휴',url:'https://www.carenation.kr/'},
{id:'v11',cat:'digital',icon:'📲',vendor:'실비아헬스',title:'Silvia 뇌 건강 앱',desc:'인지 건강 셀프체크와 일상 관리 기능을 제공하는 디지털 뇌 건강 서비스.',note:'외부 업체 정보 · 비제휴',url:'https://silviahealth.com/'},
{id:'v12',cat:'sense',icon:'🎧',vendor:'오티콘 코리아',title:'보청기·청각 보조기기',desc:'다양한 보청기 제품과 청각 관리 지원, 연결·액세서리 정보를 제공.',note:'외부 업체 정보 · 비제휴',url:'https://www.oticon.co.kr/products/hearing-aids'}
]
page.market=()=>{const items=MARKET_ITEMS.filter(x=>S.marketCategory==='all'||x.cat===S.marketCategory);return wrap(`<div class="d-flex justify-content-between align-items-start"><div><h1 class="page-title">치매 케어관</h1><p class="page-desc">돌봄에 실제로 필요한 제품·서비스군을 한곳에서 살펴보세요.</p></div><button class="btn-kimse btn-blue-k compact-btn" data-go="partnership">입점/제휴</button></div>${notice('현재는 비제휴 정보형 카탈로그입니다.','실제 입점 파트너가 생기면 광고·협찬·판매 주체를 명확히 표시합니다. 낌새가 치료·예방 효과를 보증하지 않습니다.')}<div class="market-filter">${MARKET_CATS.map(([k,i,t])=>`<button class="filter-chip ${S.marketCategory===k?'active':''}" data-market-cat="${k}">${i} ${t}</button>`).join('')}</div><div class="list market-list">${items.map(x=>`<button class="market-item" data-market-item="${x.id}"><span class="market-item-icon">${x.icon}</span><span><b class="market-vendor">${x.vendor}</b><strong>${x.title}</strong><small>${x.desc}</small><em>${x.note}</em></span>${I('chevron-right')}</button>`).join('')}</div><section class="partner-cta"><strong>제품·서비스를 제공하는 사업자이신가요?</strong><p>입점, 서비스 제휴, 광고, 공동사업 제안을 한 곳에서 받습니다.</p><button class="btn-kimse btn-secondary-k btn-full" data-go="partnership">입점·제휴 문의</button></section>`,{title:'치매 케어관',narrow:true})};
page['market-detail']=()=>{const x=MARKET_ITEMS.find(i=>i.id===S.marketItem)||MARKET_ITEMS[0],fav=S.marketFavorites.includes(x.id);return wrap(`<div class="eyebrow">${x.icon} ${x.vendor}</div><h1 class="page-title">${x.title}</h1><div class="summary-card"><p>${x.desc}</p><div class="tag-row"><span class="status-pill">비제휴 정보</span><span class="status-pill neutral">${x.note}</span></div></div>${notice('선택 전 확인하세요.','사용자의 건강상태, 의료기기 여부, 설치·통신 조건, 개인정보 처리방침을 실제 제공처에서 확인해야 합니다.')}<div class="hero-actions"><a class="btn-kimse btn-primary-k" href="${x.url}" target="_blank" rel="noopener">업체 공식 페이지 보기 ${I('external-link')}</a><button class="btn-kimse ${fav?'btn-secondary-k':'btn-blue-k'}" data-market-fav="${x.id}">${fav?'관심 저장됨 ✓':'관심 품목 저장'}</button><button class="btn-kimse btn-secondary-k" data-go="partnership">이 분야 입점·제휴 제안</button></div>`,{title:'케어관 상세',narrow:true})};
page.partnership=()=>wrap(`<h1 class="page-title">입점·제휴 문의</h1><p class="page-desc">상품 입점, 돌봄 서비스, 광고, 공동사업 제안을 구분해 접수합니다.</p><div class="form-stack"><div class="field"><label for="partner-type">문의 유형</label><select id="partner-type"><option value="PRODUCT">상품 입점</option><option value="SERVICE">서비스 제휴</option><option value="AD">광고/콘텐츠 제휴</option><option value="COOPERATION">공동사업/기관 협력</option></select></div><div class="field"><label for="partner-company">회사/기관명</label><input id="partner-company" placeholder="회사 또는 기관명"></div><div class="field"><label for="partner-name">담당자명</label><input id="partner-name" placeholder="담당자 이름"></div><div class="field"><label for="partner-email">이메일</label><input id="partner-email" type="email" placeholder="partner@example.com"></div><div class="field"><label for="partner-phone">연락처</label><input id="partner-phone" inputmode="tel" placeholder="선택 입력"></div><div class="field"><label for="partner-web">회사/서비스 URL</label><input id="partner-web" inputmode="url" placeholder="선택 입력"></div><div class="field"><label for="partner-category">카테고리</label><select id="partner-category">${MARKET_CATS.filter(x=>x[0]!=='all').map(x=>`<option value="${x[2]}">${x[2]}</option>`).join('')}</select></div><div class="field"><label for="partner-message">제안 내용</label><textarea id="partner-message" rows="6" placeholder="제품/서비스, 대상 사용자, 제공 지역, 인증·허가 여부, 제휴 방식 등을 적어주세요."></textarea></div><label class="consent-row"><input id="partner-consent" type="checkbox"> <span>문의 처리를 위한 담당자 연락정보 저장에 동의합니다.</span></label><button id="partner-submit" class="btn-kimse btn-primary-k">문의 접수</button></div>${notice('입점이 자동 승인되는 것은 아닙니다.','접수 후 적합성·표시 기준·의료/광고 표현·개인정보 처리 여부를 확인한 뒤 별도로 안내합니다.')}`,{title:'입점·제휴 문의',narrow:true});
page.plan=()=>wrap(`<h1 class="page-title">구독 플랜</h1><div class="plan-grid"><div class="plan"><h3>기본 무료</h3><div class="price">0원</div><p>비상상태 알림 수신자 1인 포함</p></div><div class="plan featured"><h3>프리미엄</h3><div class="price">알림 확장</div><p>비상상태 알림 수신자 2인 이상, 가족 다중 알림, 상세 리포트</p><button id="premium" class="btn-kimse btn-primary-k btn-full">비상알림 2인 이상 사용</button></div></div>${notice('실제 가격은 아직 확정하지 않았습니다.','결제사와 가격을 임의로 만들지 않습니다.')}`,{title:'구독 플랜'});
page.accessibility=()=>{let R=[['largeText','글자 크게 보기'],['highContrast','고대비 모드'],['voiceGuidance','음성 안내 (화면·버튼·완료)'],['soundEffects','효과음 (선택·완료·경고)'],['captions','자막 / 텍스트 대체'],['largeTouchTargets','큰 터치 영역'],['colorIcons','색상 + 아이콘 병행'],['screenReader','화면 읽기 지원'],['reduceMotion','동작 최소화']];return wrap(`<h1 class="page-title">접근성 설정</h1><p class="page-desc">고령층·저시력/시각장애·청각장애·색각 이상·운동장애를 기본 범위로 지원합니다.</p><div class="summary-card">${R.map(([k,t])=>`<div class="switch-row"><label for="a-${k}">${t}</label><input id="a-${k}" class="switch" type="checkbox" data-a11y="${k}" ${S.a11y[k]?'checked':''}></div>`).join('')}</div>${notice('시청각 동시중복장애','촉각/모스 인터페이스는 후속 단계로 분리했습니다.')}`,{title:'접근성 설정',narrow:true})};
page['admin-partners']=()=>{const token=sessionStorage.getItem('kimse.admin.token')||'';return wrap(`<h1 class="page-title">제휴 문의 관리자</h1><p class="page-desc">입점·제휴 문의를 확인하고 처리 상태를 관리합니다.</p>${token?`<div class="d-flex justify-content-between align-items-center mb-3"><span class="context-chip">운영자 인증됨</span><button class="btn-kimse btn-secondary-k compact-btn" id="admin-logout">로그아웃</button></div><div id="admin-inquiry-list" class="list"><div class="empty-state"><h3>문의 목록을 불러오는 중…</h3></div></div>`:`<div class="summary-card"><div class="field"><label for="admin-token">운영자 접근 코드</label><input id="admin-token" type="password" autocomplete="current-password" placeholder="운영자 접근 코드"></div><button id="admin-login" class="btn-kimse btn-primary-k btn-full mt-3">문의함 열기</button></div>`}`,{title:'제휴 문의 관리자',narrow:true})};
async function loadAdminInquiries(){
  const token=sessionStorage.getItem('kimse.admin.token');
  if(!token)return;
  const box=$('#admin-inquiry-list');
  if(!box)return;
  try{
    const r=await fetch(API+'/api/v1/admin/partner-inquiries?limit=100',{headers:{'X-KIMSE-ADMIN-TOKEN':token}});
    if(r.status===401||r.status===403){
      sessionStorage.removeItem('kimse.admin.token');
      feedback('운영자 접근 코드를 다시 확인해주세요.','warning');
      render();
      return;
    }
    if(!r.ok)throw new Error('HTTP '+r.status);
    const rows=await r.json();
    box.innerHTML=rows.length?rows.map(x=>`<article class="admin-inquiry"><div class="d-flex justify-content-between gap-2"><div><b>${x.company_name}</b><small>${x.inquiry_type} · ${x.category}</small></div><span class="status-pill neutral">${x.status}</span></div><p>${x.message}</p><dl><div><dt>담당자</dt><dd>${x.contact_name}</dd></div><div><dt>이메일</dt><dd><a href="mailto:${x.email}">${x.email}</a></dd></div>${x.phone?`<div><dt>연락처</dt><dd><a href="tel:${x.phone}">${x.phone}</a></dd></div>`:''}${x.website_url?`<div><dt>URL</dt><dd><a href="${x.website_url}" target="_blank" rel="noopener">공식 페이지</a></dd></div>`:''}</dl><div class="admin-status-actions">${[['REVIEWING','검토중'],['CONTACTED','연락완료'],['CLOSED','종료']].map(([v,t])=>`<button class="filter-chip ${x.status===v?'active':''}" data-admin-status="${v}" data-inquiry-id="${x.id}">${t}</button>`).join('')}</div></article>`).join(''):'<div class="empty-state"><h3>접수된 문의가 없어요</h3></div>';
  }catch(err){
    box.innerHTML='<div class="notice danger"><strong>문의함을 불러오지 못했습니다.</strong>잠시 뒤 다시 시도해주세요.</div>';
  }
}
page.settings=()=>{demo();return wrap(`<h1 class="page-title">설정</h1><div class="summary-card"><h3>${S.account.name}</h3><p>${S.account.email}</p></div><div class="list"><a class="list-row" href="#/account">내 프로필 / 역할 관리 ${I('chevron-right')}</a><a class="list-row" href="#/family">가족 / 보호자 관리 ${I('chevron-right')}</a><a class="list-row" href="#/accessibility">접근성 설정 ${I('chevron-right')}</a><a class="list-row" href="#/plan">구독 관리 ${I('chevron-right')}</a><a class="list-row" href="#/market">치매 케어관 ${I('chevron-right')}</a><a class="list-row" href="#/partnership">사업자 입점 / 제휴 문의 ${I('chevron-right')}</a><a class="list-row" href="#/admin-partners">${I('lock')} 운영자 제휴 문의함 ${I('chevron-right')}</a><a class="list-row" href="${evidenceUrl()}" target="_blank">연구 근거 / Evidence ${I('external-link')}</a></div>`,{title:'설정',narrow:true})};
function applyA11y(){document.documentElement.classList.toggle('large-text',S.a11y.largeText);document.documentElement.classList.toggle('large-touch',S.a11y.largeTouchTargets);document.documentElement.classList.toggle('high-contrast',S.a11y.highContrast)}
function render(){applyA11y();let r=route(),f=page[r]||page.start;A.innerHTML=f();setTimeout(()=>$('#main')?.focus({preventScroll:true}),0);if(r==='admin-partners'&&sessionStorage.getItem('kimse.admin.token'))setTimeout(loadAdminInquiries,20);document.title='낌새 · '+r;if(r!==lastSpokenRoute){lastSpokenRoute=r;setTimeout(()=>{const h=$('#main h1')?.innerText||$('.app-header strong')?.innerText||'낌새';if(S.a11y.voiceGuidance)say(h+' 화면입니다.')},160)}}
document.addEventListener('click',e=>{let t=e.target.closest('[data-go],[data-back],[data-role],[data-mode],[data-add-role],[data-answer],[data-med],[data-med-id],[data-mood],[data-training],[data-training-answer],[data-training-reset],[data-health],[data-market-cat],[data-market-item],[data-market-fav]');if(!t)return;if(t.dataset.go){tone('tap');go(t.dataset.go)}if(t.hasAttribute('data-back'))history.length>1?history.back():go('start');if(t.dataset.role){S.intent=t.dataset.role;S.self=['self','both'].includes(S.intent);S.care=['care','both'].includes(S.intent);save();go('auth')}if(t.dataset.mode){S.mode=t.dataset.mode;save();go(S.mode==='care'?'caregiver-home':'home')}if(t.dataset.addRole){S[t.dataset.addRole]=true;S.mode=t.dataset.addRole==='care'?'care':'self';save();go(S.mode==='care'?'caregiver-home':'home')}if(t.dataset.answer!==undefined){S.answers[S.q]=+t.dataset.answer;save();feedback('선택했습니다.');render()}if(t.hasAttribute('data-med')){S.med=!S.med;save();feedback(S.med?'복용 완료로 기록했습니다.':'복용 기록을 취소했습니다.',S.med?'success':'tap');render()}if(t.dataset.medId){const m=S.medicines.find(x=>x.id===t.dataset.medId);if(m){m.taken=!m.taken;save();feedback(m.name+(m.taken?' 복용 완료로 기록했습니다.':' 복용 기록을 취소했습니다.'),m.taken?'success':'tap');render()}}if(t.dataset.mood){S.mood=t.dataset.mood;save();feedback('오늘의 기분을 '+S.mood+'로 기록했습니다.','success');render()}if(t.dataset.training){S.selectedTraining=t.dataset.training;S.trainingResult=null;save();go('training-play')}if(t.dataset.trainingAnswer!==undefined){const x=TRAINING[S.selectedTraining]||TRAINING.memory;const correct=+t.dataset.trainingAnswer===x.correct;S.trainingResult={type:S.selectedTraining,correct};save();feedback(correct?'정답입니다. 잘했어요.':'괜찮아요. 해설을 확인해보세요.',correct?'success':'warning');render()}if(t.hasAttribute('data-training-reset')){S.trainingResult=null;save();feedback('훈련을 다시 시작합니다.');render()}if(t.dataset.health){S.selectedHealth=t.dataset.health;save();go('health-detail')}if(t.dataset.marketCat){S.marketCategory=t.dataset.marketCat;save();feedback('케어관 카테고리를 변경했습니다.');render()}if(t.dataset.marketItem){S.marketItem=t.dataset.marketItem;save();go('market-detail')}if(t.dataset.marketFav){const id=t.dataset.marketFav,i=S.marketFavorites.indexOf(id);if(i>=0)S.marketFavorites.splice(i,1);else S.marketFavorites.push(id);save();feedback(i>=0?'관심 품목에서 해제했습니다.':'관심 품목에 저장했습니다.','success');render()}});
document.addEventListener('change',e=>{if(e.target.dataset.a11y){S.a11y[e.target.dataset.a11y]=e.target.checked;save();render();feedback(e.target.closest('.switch-row').innerText+(e.target.checked?' 켰습니다':' 껐습니다'),e.target.checked?'success':'tap')}});
document.addEventListener('click',e=>{if(e.target.id==='signup'){S.account={name:$('#name').value.trim()||'김○○',email:$('#email').value.trim()||'kimse@example.com'};S.mode=S.intent==='care'?'care':'self';save();go(S.mode==='care'?'caregiver-home':'home')}if(e.target.id==='begin'){S.q=0;S.answers=[];save();go('assessment')}if(e.target.id==='next'){if(S.answers[S.q]===undefined)return;if(S.q>=Q.length-1)go('result');else{S.q++;save();render()}}if(e.target.id==='save-family'){const name=$('#family-name').value.trim(),relation=$('#family-relation').value.trim();if(!name){feedback('이름을 입력해주세요.','warning');return}S.caregivers.push({name,relation:relation||'가족'});save();feedback('보호자 연결 정보를 저장했습니다.','success');go('family')}if(e.target.id==='save-alert'){const name=$('#alert-name').value.trim(),relation=$('#alert-relation').value.trim(),phone=$('#alert-phone').value.trim();if(!name||!phone){feedback('이름과 연락처를 입력해주세요.','warning');return}if(S.alertRecipients.length>=1&&S.plan!=='PREMIUM'){feedback('비상알림 수신자 2인째부터 구독이 필요합니다.','warning');go('plan')}else{S.alertRecipients.push({name,relation:relation||'가족',phone});save();feedback('비상알림 수신자를 저장했습니다.','success');go('emergency')}}if(e.target.id==='save-med'){const name=$('#med-name').value.trim(),time=$('#med-time').value||'08:00',note=$('#med-note').value.trim();if(!name){feedback('약 이름을 입력해주세요.','warning');return}S.medicines.push({id:'m'+Date.now(),name,time,note,taken:false});save();feedback('약을 등록했습니다.','success');go('medication')}if(e.target.id==='save-health'){const k=S.selectedHealth in HEALTH_META?S.selectedHealth:'sleep',v=$('#health-value').value.trim();if(!v){feedback('기록할 값을 입력해주세요.','warning');return}S.health[k]=v;S.health.memo=$('#health-memo').value.trim();save();feedback(HEALTH_META[k][1]+' 기록을 저장했습니다.','success');go('health')}if(e.target.id==='add-schedule'){const title=$('#schedule-title').value.trim(),date=$('#schedule-date').value.trim();if(!title||!date){feedback('일정과 날짜/시간을 입력해주세요.','warning');return}S.schedule.push({id:'s'+Date.now(),title,date});save();feedback('가족 일정을 추가했습니다.','success');render()}if(e.target.id==='premium'){S.plan='PREMIUM';save();feedback('비상알림 수신자 확장 기능이 적용되었습니다.','success');go('emergency')}});
document.addEventListener('click',async e=>{if(e.target.id==='admin-login'){const token=$('#admin-token').value.trim();if(!token){feedback('운영자 접근 코드를 입력해주세요.','warning');return}sessionStorage.setItem('kimse.admin.token',token);feedback('운영자 문의함을 확인합니다.');render();return}if(e.target.id==='admin-logout'){sessionStorage.removeItem('kimse.admin.token');feedback('운영자 문의함에서 로그아웃했습니다.');render();return}const statusBtn=e.target.closest('[data-admin-status]');if(statusBtn){const token=sessionStorage.getItem('kimse.admin.token');if(!token)return;statusBtn.disabled=true;try{const r=await fetch(API+'/api/v1/admin/partner-inquiries/'+encodeURIComponent(statusBtn.dataset.inquiryId)+'/status',{method:'POST',headers:{'Content-Type':'application/json','X-KIMSE-ADMIN-TOKEN':token},body:JSON.stringify({status:statusBtn.dataset.adminStatus})});if(!r.ok)throw new Error('HTTP '+r.status);feedback('문의 상태를 변경했습니다.','success');await loadAdminInquiries()}catch{feedback('문의 상태 변경에 실패했습니다.','warning');statusBtn.disabled=false}}});
document.addEventListener('click',async e=>{if(e.target.id!=='partner-submit')return;const company=$('#partner-company').value.trim(),contact=$('#partner-name').value.trim(),email=$('#partner-email').value.trim(),message=$('#partner-message').value.trim();if(!company||!contact||!email||message.length<10||!$('#partner-consent').checked){feedback('회사명, 담당자, 이메일, 10자 이상의 제안 내용과 개인정보 동의를 확인해주세요.','warning');return}e.target.disabled=true;e.target.textContent='접수 중…';try{const r=await fetch(API+'/api/v1/partner-inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inquiry_type:$('#partner-type').value,company_name:company,contact_name:contact,email,phone:$('#partner-phone').value.trim()||null,website_url:$('#partner-web').value.trim()||null,category:$('#partner-category').value,message})});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();S.partnerStatus={id:data.id,at:data.created_at,company};save();feedback('입점·제휴 문의가 정상 접수되었습니다.','success');A.innerHTML=wrap(`<h1 class="page-title">문의가 접수됐어요</h1>${notice('접수 완료',company+' 담당자님의 제안을 저장했습니다. 검토 후 입력한 이메일로 연락드릴 수 있습니다.')}<button class="btn-kimse btn-primary-k btn-full" data-go="market">케어관으로 돌아가기</button>`,{title:'문의 접수',narrow:true})}catch(err){feedback('접수에 실패했습니다. 네트워크 상태를 확인하고 다시 시도해주세요.','warning');e.target.disabled=false;e.target.textContent='문의 접수'}});

window.addEventListener('hashchange',render);window.addEventListener('online',()=>{O.hidden=true;say('인터넷 연결이 복구되었습니다.')});window.addEventListener('offline',()=>{O.hidden=false;say('인터넷 연결이 끊겼습니다.')});O.hidden=navigator.onLine;
async function bootstrap(){await loadEvidenceModel();render();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
bootstrap();
})();